export const DUMMY_DATA = {
  id: 1,
  a: "/Gidle/images.jpg",
  album: "Gidle",
  singer: "Gidle",
  list: [
    {
      number: 1,
      song: "HANN",
      time: "03:44",
      url: "/Gidle/(G)I-DLE-HANN.mp3",
    },
    {
      number: 2,
      song: "LATATA",
      time: "03:41",
      url: "/Gidle/(G)I-DLE-LATATA.mp3",
    },
    {
      number: 3,
      song: "Nxde",
      time: "03:03",
      url: "/Gidle/(G)I-DLE-Nxde.mp3",
    },
    {
      number: 4,
      song: "EAM BEAM",
      time: "02:52",
      url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
    },
    {
      number: 5,
      song: "Oh my god",
      time: "03:20",
      url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
    },
    {
      number: 6,
      song: "LION",
      time: "03:38",
      url: "/Gidle/(G)I-DLE-LION.mp3",
    },
    {
      number: 7,
      song: "Senorita",
      time: "03:44",
      url: "/Gidle/(G)I-DLE-Senorita.mp3",
    },
  ],
  fulltime: "24:02",
};

export const DUMMY_ALBUMHOT = [
  {
    id: 1,
    a: "/Gidle/images.jpg",
    album: "Gidle",
    singer: "Gidle",
    list: [
      {
        number: 1,
        song: "HANN",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "LATATA",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "Nxde",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "EAM BEAM",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "Oh my god",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "LION",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "Senorita",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/BIGBANG.jpg",
    album: "BigBang",
    singer: "BigBang",
    list: [
      {
        number: 1,
        song: "LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Monster",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "TONIGHT",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "BLUE",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "BANG BANG BANG",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "BAD BOY",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "LET'S NOT FALL IN LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/ED.png",
    album: "EdSheeran",
    singer: "EdSheeran",
    list: [
      {
        number: 1,
        song: "Happie",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "PokemonCelestial",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "Remember The Name",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "River",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Near",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Shape Of You",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Perfect",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/150773404846439.jpg",
    album: "Eminem",
    singer: "Eminem",
    list: [
      {
        number: 1,
        song: "Godzilla",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gone",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Sorry",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mockingbird",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "Mistake",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "Venom",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Rescue me",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Detective.jpg",
    album: "Cartoon",
    singer: "Cartoon",
    list: [
      {
        number: 1,
        song: "殘響散歌",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Always",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Sign",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "OverSoul",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "The Other self",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "VOICE",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Akari",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/抖音.jpg",
    album: "抖音神曲",
    singer: "抖音神曲",
    list: [
      {
        number: 1,
        song: "熬夜成癮",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "一百萬個可能",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "说散就散",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "踏山河",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "你就不要想起我",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "追光者",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "好可惜",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];

export const DUMMY_ALBUMNEW = [
  {
    id: 1,
    a: "/Gidle/BlackPink.jpg",
    album: "BlackPink",
    singer: "BlackPink",
    list: [
      {
        number: 1,
        song: "AS IF IT'S YOUR LAST",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "STAY",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "BOOMBAYAH",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "PLAYING WITH FIRE",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "KILL THIS LOVE",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "HOW YOU LIKE THAT",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "PINK VENOM",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/Alin.jpg",
    album: "LINK",
    singer: "Alin",
    list: [
      {
        number: 1,
        song: "摯友",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "舞夜巴黎",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "盡情旋轉",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "我怨",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "聊聊天",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "自信與美麗",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "給未來",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/AlenWalker.jpg",
    album: "Sped up",
    singer: "Alen Walker",
    list: [
      {
        number: 1,
        song: "All Falls Down",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "Alone",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "Darkside",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "The Spectre",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Diamond Heart",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "On My Way ",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Man On The Moon",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/林俊傑.jpg",
    album: "重拾快樂",
    singer: "林俊傑",
    list: [
      {
        number: 1,
        song: "Castle In The Air",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "孤獨娛樂",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "一時的選擇",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "自畫像",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "如果我還剩一件事情可以做",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "夢不凌亂",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "謝幕",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/kenyagrace.jpg",
    album: "Only In My Mind",
    singer: "Kenya Grace",
    list: [
      {
        number: 1,
        song: "Afterparty Lover",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Meteor",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Strangers",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "Oranges",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "Obsessed",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "Someone Else",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Only In My Mind",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/Lauv.jpg",
    album: "All 4 Nothing",
    singer: "Lauv",
    list: [
      {
        number: 1,
        song: "Better Than This",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "Forever",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "Molly in Mexico",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "All 4 Nothing",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "I (Don’t) Have a Problem",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "Hey Ari",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "Kids Are Born Stars",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];

export const DUMMY_ALBUMRECOMMEND = [
  {
    id: 1,
    a: "/Gidle/五月天.jpg",
    album: "諾亞方舟",
    singer: "MayDay",
    list: [
      {
        number: 1,
        song: "2012",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "夜訪吸血鬼",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "你不是真正的快樂",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "第二人生",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "突然好想你",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "倔強",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "諾亞方舟",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/LinkinPark.jpg",
    album: "Meteora",
    singer: "Linkin Park",
    list: [
      {
        number: 1,
        song: "Lying From You",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Somewhere I Belong",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "Easier To Run",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "Breaking The Habit",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "From The Inside",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "Numb",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "Faint",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/Flow.jpg",
    album: "ANIME BEST",
    singer: "FLOW",
    list: [
      {
        number: 1,
        song: "Go!!!",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "Re:member",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "Colors",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "Sign",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Calling",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Realize",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Summer Freak",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/少女時代.jpg",
    album: "The Best",
    singer: "Girls' Generation",
    list: [
      {
        number: 1,
        song: "Genie",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gee",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Run Devil Run",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mr.Taxi",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "The Boys",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "I Got A Boy",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Oh!",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Eason.jpg",
    album: "Rice & Shine",
    singer: "陳奕迅",
    list: [
      {
        number: 1,
        song: "可以了",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "愚人快樂",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "你給我聽好",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "放棄治療",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "時光隧道",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "陰天快樂",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "對面",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/Avicii.jpg",
    album: "TIM",
    singer: "Avicii",
    list: [
      {
        number: 1,
        song: "Fades Away",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "Excuse Me Mr Sir",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "SOS",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "Ain't A Thing",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "Heart Upon My Sleeve",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "Never Leave Me",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "Freak",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];
export const DUMMY_ALBUMFEATURED = [
  {
    id: 1,
    a: "/Gidle/IU.jpg",
    album: "LILAC",
    singer: "IU",
    list: [
      {
        number: 1,
        song: "Troll",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "Epilogue",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "Celebrity",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "Empty Cup",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "Coin",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "Hi spring Bye",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "My sea",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/周興哲.jpg",
    album: "如果雨之後",
    singer: "周興哲",
    list: [
      {
        number: 1,
        song: "如果雨之後",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Without Her",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "易碎品",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "Another You",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "永不失聯的愛",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "快樂一次擁有",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "我知道要微笑",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/婁峻碩.jpg",
    album: "BOARDING",
    singer: "婁峻碩",
    list: [
      {
        number: 1,
        song: "BLUE SKY",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "STAY BYE",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "80",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "SOFA",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "COLORFUL",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "AIRPLANE",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "NEVER LAND",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/5566.jpg",
    album: "喝采",
    singer: "5566",
    list: [
      {
        number: 1,
        song: "我難過",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "存在",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "偷心",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "哇撒米",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "同一個世界",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "摯愛",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "守候",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/imagedragon.jpg",
    album: "Bones",
    singer: "Image Dragon",
    list: [
      {
        number: 1,
        song: "Bones",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Believer",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Enemy",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "Warriors",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "Natural",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "Radioactive",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Demons",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    album: "Amier",
    a: "/music/maxresdefault.jpg",
    singer: "Amier",
    list: [
      {
        number: 1,
        song: "Refrain",
        time: "04:46",
        url: "/music/Aimer-Refrain.mp3",
      },
      {
        number: 2,
        song: "灰色と青",
        time: "05:29",
        url: "/music/BOOTLEG%20-%20米津玄師%20-%20灰色と青.mp3",
      },
      {
        number: 3,
        song: "天氣之子",
        time: "05:33",
        url: "/music/天氣之子.mp3",
      },
      {
        number: 4,
        song: "Sleepless Nights",
        time: "04:11",
        url: "/music/Aimer-Sleepless Nights.mp3",
      },
      {
        number: 5,
        song: "飽和",
        time: "03:17",
        url: "/music/Ayase-飽和.mp3",
      },
      {
        number: 6,
        song: "The Biggest Dreamer",
        time: "03:50",
        url: "/music/數碼寶貝-TheBiggestDreamer.mp3",
      },
      {
        number: 7,
        song: "Lemon",
        time: "04:34",
        url: "/music/米津玄師-Lemon.mp3",
      },
    ],
    fulltime: "31:40",
  },
];
