export const DUMMY_DATA = {
  id: 1,
  album: "Amier",
  a: "/music/maxresdefault.jpg",
  singer: "Amier",
  list: [
    {
      number: 1,
      song: "Refrain",
      time: "04:46",
      url: "/music/Aimer-Refrain.mp3",
    },
    {
      number: 2,
      song: "灰色と青",
      time: "05:29",
      url: "/music/BOOTLEG%20-%20米津玄師%20-%20灰色と青.mp3",
    },
    {
      number: 3,
      song: "天氣之子",
      time: "05:33",
      url: "/music/天氣之子.mp3",
    },
    {
      number: 4,
      song: "Sleepless Nights",
      time: "04:11",
      url: "/music/Aimer-Sleepless Nights.mp3",
    },
    {
      number: 5,
      song: "飽和",
      time: "03:17",
      url: "/music/Ayase-飽和.mp3",
    },
    {
      number: 6,
      song: "The Biggest Dreamer",
      time: "03:50",
      url: "/music/數碼寶貝-TheBiggestDreamer.mp3",
    },
    {
      number: 7,
      song: "Lemon",
      time: "04:34",
      url: "/music/米津玄師-Lemon.mp3",
    },
  ],
  fulltime: "31:40",
};

export const DUMMY_ALBUMHOT = [
  {
    id: 1,
    a: "/Gidle/images.jpg",
    album: "Gidle",
    singer: "Gidle",
    list: [
      {
        number: 1,
        song: "HANN",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "LATATA",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "Nxde",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "EAM BEAM",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "Oh my god",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "LION",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "Senorita",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/BIGBANG.jpg",
    album: "BigBang",
    singer: "BigBang",
    list: [
      {
        number: 1,
        song: "LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Monster",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "TONIGHT",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "BLUE",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "BANG BANG BANG",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "BAD BOY",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "LET'S NOT FALL IN LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/ED.png",
    album: "EdSheeran",
    singer: "EdSheeran",
    list: [
      {
        number: 1,
        song: "Happie",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "PokemonCelestial",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "RememberTheName",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "River",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Near",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Shape Of You",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Perfect",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/150773404846439.jpg",
    album: "Eminem",
    singer: "Eminem",
    list: [
      {
        number: 1,
        song: "Godzilla",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gone",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Sorry",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mockingbird",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "Mistake",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "Venom",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Rescue me",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Detective.jpg",
    album: "Cartoon",
    singer: "Cartoon",
    list: [
      {
        number: 1,
        song: "殘響散歌",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Always",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Sign",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "OverSoul",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "The Other self",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "VOICE",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Akari",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/抖音.jpg",
    album: "抖音神曲",
    singer: "抖音神曲",
    list: [
      {
        number: 1,
        song: "熬夜成癮",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "一百萬個可能",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "说散就散",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "踏山河",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "你就不要想起我",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "追光者",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "好可惜",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];

export const DUMMY_ALBUMNEW = [
  {
    id: 1,
    a: "/Gidle/BlackPink.jpg",
    album: "BlackPink",
    singer: "BlackPink",
    list: [
      {
        number: 1,
        song: "AS IF IT'S YOUR LAST",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "STAY",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "BOOMBAYAH",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "PLAYING WITH FIRE",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "KILL THIS LOVE",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "HOW YOU LIKE THAT",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "PINK VENOM",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/BIGBANG.jpg",
    album: "BigBang",
    singer: "BigBang",
    list: [
      {
        number: 1,
        song: "LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Monster",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "TONIGHT",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "BLUE",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "BANG BANG BANG",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "BAD BOY",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "LET'S NOT FALL IN LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/ED.png",
    album: "EdSheeran",
    singer: "EdSheeran",
    list: [
      {
        number: 1,
        song: "Happie",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "PokemonCelestial",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "RememberTheName",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "River",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Near",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Shape Of You",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Perfect",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/150773404846439.jpg",
    album: "Eminem",
    singer: "Eminem",
    list: [
      {
        number: 1,
        song: "Godzilla",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gone",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Sorry",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mockingbird",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "Mistake",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "Venom",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Rescue me",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Detective.jpg",
    album: "Cartoon",
    singer: "Cartoon",
    list: [
      {
        number: 1,
        song: "殘響散歌",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Always",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Sign",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "OverSoul",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "The Other self",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "VOICE",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Akari",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/抖音.jpg",
    album: "抖音神曲",
    singer: "抖音神曲",
    list: [
      {
        number: 1,
        song: "熬夜成癮",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "一百萬個可能",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "说散就散",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "踏山河",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "你就不要想起我",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "追光者",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "好可惜",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];

export const DUMMY_ALBUMRECOMMEND = [
  {
    id: 1,
    a: "/Gidle/images.jpg",
    album: "Gidle",
    singer: "Gidle",
    list: [
      {
        number: 1,
        song: "HANN",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "LATATA",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "Nxde",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "EAM BEAM",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "Oh my god",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "LION",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "Senorita",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/BIGBANG.jpg",
    album: "BigBang",
    singer: "BigBang",
    list: [
      {
        number: 1,
        song: "LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Monster",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "TONIGHT",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "BLUE",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "BANG BANG BANG",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "BAD BOY",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "LET'S NOT FALL IN LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/ED.png",
    album: "EdSheeran",
    singer: "EdSheeran",
    list: [
      {
        number: 1,
        song: "Happie",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "PokemonCelestial",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "RememberTheName",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "River",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Near",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Shape Of You",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Perfect",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/150773404846439.jpg",
    album: "Eminem",
    singer: "Eminem",
    list: [
      {
        number: 1,
        song: "Godzilla",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gone",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Sorry",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mockingbird",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "Mistake",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "Venom",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Rescue me",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Detective.jpg",
    album: "Cartoon",
    singer: "Cartoon",
    list: [
      {
        number: 1,
        song: "殘響散歌",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Always",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Sign",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "OverSoul",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "The Other self",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "VOICE",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Akari",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/抖音.jpg",
    album: "抖音神曲",
    singer: "抖音神曲",
    list: [
      {
        number: 1,
        song: "熬夜成癮",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "一百萬個可能",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "说散就散",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "踏山河",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "你就不要想起我",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "追光者",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "好可惜",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];
export const DUMMY_ALBUMFEATURED = [
  {
    id: 1,
    a: "/Gidle/images.jpg",
    album: "Gidle",
    singer: "Gidle",
    list: [
      {
        number: 1,
        song: "HANN",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-HANN.mp3",
      },
      {
        number: 2,
        song: "LATATA",
        time: "03:41",
        url: "/Gidle/(G)I-DLE-LATATA.mp3",
      },
      {
        number: 3,
        song: "Nxde",
        time: "03:03",
        url: "/Gidle/(G)I-DLE-Nxde.mp3",
      },
      {
        number: 4,
        song: "EAM BEAM",
        time: "02:52",
        url: "/Gidle/(G)I-DLE-EAMBEAM.mp3",
      },
      {
        number: 5,
        song: "Oh my god",
        time: "03:20",
        url: "/Gidle/(G)I-DLE-Ohmygod.mp3",
      },
      {
        number: 6,
        song: "LION",
        time: "03:38",
        url: "/Gidle/(G)I-DLE-LION.mp3",
      },
      {
        number: 7,
        song: "Senorita",
        time: "03:44",
        url: "/Gidle/(G)I-DLE-Senorita.mp3",
      },
    ],
    fulltime: "24:02",
  },
  {
    id: 2,
    a: "/BigBang/BIGBANG.jpg",
    album: "BigBang",
    singer: "BigBang",
    list: [
      {
        number: 1,
        song: "LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LOVE.mp3",
      },
      {
        number: 2,
        song: "Monster",
        time: "03:46",
        url: "/BigBang/BIGBANG-Monster.mp3",
      },
      {
        number: 3,
        song: "TONIGHT",
        time: "03:43",
        url: "/BigBang/BIGBANG-TONIGHT.mp3",
      },
      {
        number: 4,
        song: "BLUE",
        time: "04:02",
        url: "/BigBang/BIGBANG-BLUE.mp3",
      },
      {
        number: 5,
        song: "BANG BANG BANG",
        time: "03:49",
        url: "/BigBang/BIGBANG-BANGBANGBANG.mp3",
      },
      {
        number: 6,
        song: "BAD BOY",
        time: "03:57",
        url: "/BigBang/BIGBANG-BADBOY.mp3",
      },
      {
        number: 7,
        song: "LET'S NOT FALL IN LOVE",
        time: "03:48",
        url: "/BigBang/BIGBANG-LETSNOTFALLINLOVE.mp3",
      },
    ],
    fulltime: "26:53",
  },
  {
    id: 3,
    a: "/EdSheeran/ED.png",
    album: "EdSheeran",
    singer: "EdSheeran",
    list: [
      {
        number: 1,
        song: "Happie",
        time: "03:25",
        url: "/EdSheeran/EdSheeran-Happie.mp3",
      },
      {
        number: 2,
        song: "PokemonCelestial",
        time: "03:29",
        url: "/EdSheeran/EdSheeran-PokemonCelestial.mp3",
      },
      {
        number: 3,
        song: "RememberTheName",
        time: "03:27",
        url: "/EdSheeran/EdSheeran-RememberTheName.mp3",
      },
      {
        number: 4,
        song: "River",
        time: "03:41",
        url: "/EdSheeran/EdSheeran-River.mp3",
      },
      {
        number: 5,
        song: "Near",
        time: "03:19",
        url: "/EdSheeran/EdSheeran-Near.mp3",
      },
      {
        number: 6,
        song: "Shape Of You",
        time: "03:55",
        url: "/EdSheeran/EdSheeran-ShapeOfYou.mp3",
      },
      {
        number: 7,
        song: "Perfect",
        time: "04:28",
        url: "/EdSheeran/EdSheeran-Perfect.mp3",
      },
    ],
    fulltime: "25:44",
  },
  {
    id: 4,
    a: "/Eminem/150773404846439.jpg",
    album: "Eminem",
    singer: "Eminem",
    list: [
      {
        number: 1,
        song: "Godzilla",
        time: "03:30",
        url: "/Eminem/Eminem-Godzilla.mp3",
      },
      {
        number: 2,
        song: "Gone",
        time: "04:11",
        url: "/Eminem/Eminem-Gone.mp3",
      },
      {
        number: 3,
        song: "Sorry",
        time: "03:17",
        url: "/Eminem/Eminem-I'mSorry.mp3",
      },
      {
        number: 4,
        song: "Mockingbird",
        time: "04:11",
        url: "/Eminem/Eminem-Mockingbird.mp3",
      },
      {
        number: 5,
        song: "Mistake",
        time: "04:17",
        url: "/Eminem/Eminem-Mistake.mp3",
      },
      {
        number: 6,
        song: "Venom",
        time: "04:39",
        url: "/Eminem/Eminem-Venom.mp3",
      },
      {
        number: 7,
        song: "Rescue me",
        time: "03:17",
        url: "/Eminem/Eminem-RESCUEME.mp3",
      },
    ],
    fulltime: "27:22",
  },
  {
    id: 5,
    a: "/Cartoon/Detective.jpg",
    album: "Cartoon",
    singer: "Cartoon",
    list: [
      {
        number: 1,
        song: "殘響散歌",
        time: "03:03",
        url: "/Cartoon/aimer-殘響散歌.mp3",
      },
      {
        number: 2,
        song: "Always",
        time: "04:08",
        url: "/Cartoon/名探偵柯南-Always.mp3",
      },
      {
        number: 3,
        song: "Sign",
        time: "03:58",
        url: "/Cartoon/火影忍者-Sign.mp3",
      },
      {
        number: 4,
        song: "OverSoul",
        time: "03:52",
        url: "/Cartoon/通靈王-OverSoul.mp3",
      },
      {
        number: 5,
        song: "The Other self",
        time: "04:44",
        url: "/Cartoon/黑子的籃球第二季OP-TheOtherself.mp3",
      },
      {
        number: 6,
        song: "VOICE",
        time: "03:27",
        url: "/Cartoon/遊戲王-VOICE.mp3",
      },
      {
        number: 7,
        song: "Akari",
        time: "03:58",
        url: "/Cartoon/崎山蒼志-燈.mp3",
      },
    ],
    fulltime: "27:10",
  },
  {
    id: 6,
    a: "/抖音神曲/抖音.jpg",
    album: "抖音神曲",
    singer: "抖音神曲",
    list: [
      {
        number: 1,
        song: "熬夜成癮",
        time: "04:16",
        url: "/抖音神曲/朱興東-熬夜成癮.mp3",
      },
      {
        number: 2,
        song: "一百萬個可能",
        time: "04:02",
        url: "/抖音神曲/虎二-一百萬個可能.mp3",
      },
      {
        number: 3,
        song: "说散就散",
        time: "03:40",
        url: "/抖音神曲/说散就散.mp3",
      },
      {
        number: 4,
        song: "踏山河",
        time: "02:49",
        url: "/抖音神曲/是七叔呢-踏山河.mp3",
      },
      {
        number: 5,
        song: "你就不要想起我",
        time: "03:40",
        url: "/抖音神曲/你就不要想起我.mp3",
      },
      {
        number: 6,
        song: "追光者",
        time: "04:06",
        url: "/抖音神曲/汪蘇瀧-追光者.mp3",
      },
      {
        number: 7,
        song: "好可惜",
        time: "05:10",
        url: "/抖音神曲/莊心妍-好可惜.mp3",
      },
    ],
    fulltime: "27:43",
  },
];
